# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.c.gwpca <- function(data, points, fields, bw, adaptive = T, kernel = "gaussian", longlat = F, k = 2) {
    kernel.i <- switch(kernel, "gaussian" = 0, "bisquare" = 2)
    .Call("gwmodelr_gwpca", PACKAGE = 'gwmodelr',
          data, points, fields, bw, adaptive, kernel, longlat, k)
}